# Operations VPC - PostgreSQL Database
# This file contains the RDS PostgreSQL instance for SQLMesh

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Operations VPC - PostgreSQL Database for SQLMesh'

Parameters:
  VpcId:
    Type: String
    Description: VPC ID
  
  PrivateSubnet1Id:
    Type: String
    Description: First private subnet ID
  
  PrivateSubnet2Id:
    Type: String
    Description: Second private subnet ID
  
  DatabasePassword:
    Type: String
    Description: Database password
    NoEcho: true
    MinLength: 8

Resources:
  # DB Subnet Group
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for SQLMesh PostgreSQL
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: ops-sqlmesh-db-subnet-group

  # Security Group for PostgreSQL
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ops-sqlmesh-postgres-sg
      GroupDescription: Security group for SQLMesh PostgreSQL
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref AccessServerSecurityGroupId
          Description: PostgreSQL from Access Server
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref SqlmeshServerSecurityGroupId
          Description: PostgreSQL from SQLMesh Server
      Tags:
        - Key: Name
          Value: ops-sqlmesh-postgres-sg

  # RDS PostgreSQL Instance
  SqlmeshPostgresDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: ops-sqlmesh-postgres
      DBName: sqlmesh
      Engine: postgres
      EngineVersion: '15.4'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp2
      StorageEncrypted: true
      MasterUsername: postgres
      MasterUserPassword: !Ref DatabasePassword
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      BackupRetentionPeriod: 7
      MultiAZ: false
      PubliclyAccessible: false
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: ops-sqlmesh-postgres

Outputs:
  DatabaseEndpoint:
    Description: PostgreSQL database endpoint
    Value: !GetAtt SqlmeshPostgresDatabase.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseEndpoint'
  
  DatabasePort:
    Description: PostgreSQL database port
    Value: !GetAtt SqlmeshPostgresDatabase.Endpoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-DatabasePort'
  
  DatabaseSecurityGroupId:
    Description: Database security group ID
    Value: !Ref DatabaseSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseSecurityGroupId'

